"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
[](fg:#212736 bg:#1d2230)\
\n$character"""

right_format = """
$cmd_duration\
$lua\
$python\
$time\
"""


[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false

# ~/.config/starship.toml


[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[lua]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = " "
style = "fg:#77FFCC bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
format = '[${symbol} ${version} $virtualenv ]($style)'
pyenv_version_name = false
pyenv_prefix = 'pyenv'

[time]
disabled = false
time_format = "%R-%A" # Hour:Minute Format
time_range = '-'
use_12hr = false
style = "bg:#1d2230"
format = '[[   $time  ](fg:#a0a9cb bg:#1d2230)]($style)'

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
